### PR TITLE
Added some sample html to index for example/lab.

### PR DESCRIPTION
**Pull request by payne-chris-r**
@berziiii just added some sample html to make the lab go smoothly. Take a look for me?

### CODE REVIEW

**Comment by gaand** [comment]
@payne-chris-r Please lowercase tag names.

**Comment by payne-chris-r** [comment]
Updated @gaand. Great catch.

**Comment by gaand** [comment]
I missed this in my last review, but this isn't based on the index.html from the current template.  I'll open an issue if necessary.

**Comment by payne-chris-r** [comment]
Yeah, this PR isn't necessary. I was going to use an HTML page to build a DOM diagram in addition to the wireframe example because I think it makes a lot of sense visually. I didn't end up using it, and it isn't necessary, but might be a nice tool in the event someone wants to do just that.

**Comment by gaand** [comment]
If obsolete, please close the pull request. If not, perhaps open an issue and also close the pull request.

**Comment by payne-chris-r** [comment]
Closing because it IS obsolete.

**Comment by jrhorn424** [comment]
> I was going to use an HTML page to build a DOM diagram in addition to the wireframe example because I think it makes a lot of sense visually.

I like that. Can you explain more? Did you have a tool that would analyze the source and produce a tree? (other than the browser, of course... 😄)

**Pull request closed without merging**
